In [1]:
from sklearn import cross_validation, datasets
import numpy as np

ImportError: ignored

In [0]:
iris = datasets.load_iris()

In [0]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(iris.data, iris.target, test_size = 0.3)

In [0]:
float(len(train_labels)) / len(iris.data)

0.7

In [0]:
print "Размер обучающей выборки : {} объектов \nРазмер тестовой выборки : {} объектов".format(len(train_data), len(test_data))

Размер обучающей выборки : 105 объектов 
Размер тестовой выборки : 45 объектов


In [0]:
print "Обучающая выборка:\n", train_data[:5]
print "\nТестовая выборка :\n", test_data[:5]

Обучающая выборка:
[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.  3.5 1.3 0.3]
 [5.6 2.5 3.9 1.1]
 [6.4 2.8 5.6 2.2]]

Тестовая выборка :
[[6.2 2.8 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.  2.2 4.  1. ]
 [6.1 3.  4.6 1.4]
 [5.4 3.9 1.3 0.4]]


In [0]:
print "Метки классов на обучающей выборке:\n", train_labels
print "\nМетки классов на тестовой выборке :\n", test_labels

Метки классов на обучающей выборке:
[2 1 0 1 2 2 1 1 2 2 1 2 1 2 2 0 0 2 1 0 0 0 0 0 1 2 2 2 0 0 2 1 2 2 2 0 0
 0 1 1 1 1 1 0 1 1 2 1 0 2 0 0 1 0 2 1 0 0 0 2 2 1 0 0 0 1 2 0 1 0 0 2 1 2
 2 1 1 0 1 1 1 1 0 2 2 0 2 2 2 2 0 2 0 1 1 0 1 1 0 2 2 2 0 2 1]

Метки классов на тестовой выборке :
[2 1 1 1 0 0 1 2 1 1 0 1 1 1 2 1 2 0 2 0 0 1 0 0 1 0 2 2 0 0 2 0 2 0 2 2 1
 1 0 2 2 1 2 1 0]


In [0]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5):
  print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [0]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 5, shuffle = True):
  print train_indices, test_indices

[0 1 2 3 5 6 7 9] [4 8]
[0 1 3 4 6 7 8 9] [2 5]
[1 2 3 4 5 6 7 8] [0 9]
[0 1 2 4 5 7 8 9] [3 6]
[0 2 3 4 5 6 8 9] [1 7]


In [0]:
for train_indices, test_indices in cross_validation.KFold(10, n_folds = 2, shuffle = True, random_state = 2):
  print train_indices, test_indices

[2 3 6 8 9] [0 1 4 5 7]
[0 1 4 5 7] [2 3 6 8 9]


In [0]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 5, shuffle = True, random_state = 0):
  print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[0 1 3 4 6 7 8 9] [2 5]
[1 2 3 4 5 6 8 9] [0 7]
[0 2 3 4 5 7 8 9] [1 6]
[0 1 2 4 5 6 7 8] [3 9]
[0 1 2 3 5 6 7 9] [4 8]


In [0]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedKFold(target, n_folds = 5, shuffle = True, random_state = 0):
  print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[0 2 3 5 6 7 8 9] [1 4]
[1 2 3 4 6 7 8 9] [0 5]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 4 5 7 8] [6 9]
[0 1 2 3 4 5 6 9] [7 8]


In [0]:
for train_indices, test_indices in cross_validation.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
  print train_indices, test_indices

[0 7 3 4 9 8 2 6] [1 5]
[9 7 2 3 4 8 0 5] [1 6]
[7 0 1 5 6 3 2 4] [9 8]
[7 2 1 5 3 9 6 8] [4 0]
[2 6 5 1 3 7 8 0] [4 9]
[9 1 5 3 2 6 4 8] [0 7]
[6 0 9 4 3 7 5 1] [2 8]
[8 6 7 1 4 5 9 2] [3 0]
[4 3 5 0 7 8 9 6] [1 2]
[0 8 3 2 1 5 6 7] [9 4]


In [0]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in cross_validation.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
  print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[0 3 5 2 9 7 1 6] [8 4]
[6 0 1 9 3 5 2 8] [4 7]
[8 0 4 9 7 1 5 3] [2 6]
[3 9 5 7 4 8 2 1] [6 0]


In [0]:
for train_indices, test_indices in cross_validation.LeaveOneOut(10):
  print train_indices, test_indices

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
